import type { Product } from "./types";

export const CATEGORIES = [
  "All",
  "Lyophilized Peptides",
  "Peptide Blends",
  "Small Molecules",
] as const;

export const products: Product[] = [
  {
    slug: "bpc-157",
    name: "BPC-157",
    category: "Lyophilized Peptides",
    casNumber: "137525-51-0",
    molecularFormula: "C62H98N16O22",
    molecularWeight: "1419.53 g/mol",
    purityPercent: 99.2,
    sequenceOrForm: "Gly-Glu-Pro-Pro-Pro-Gly-Lys-Pro-Ala-Asp-Asp-Ala-Gly-Leu-Val",
    storage: "Lyophilized powder. Store at -20°C, protect from light and moisture.",
    sizes: [
      { label: "5 mg", priceUsd: 42 },
      { label: "10 mg", priceUsd: 68 },
      { label: "15 mg", priceUsd: 94 },
    ],
    batchNumbers: ["VC-BPC-2411", "VC-BPC-2502"],
    summary: "Synthetic pentadecapeptide, HPLC-verified purity, supplied as lyophilized powder.",
    description: [
      "BPC-157 is a synthetic peptide chain of fifteen residues, supplied strictly for in-vitro and laboratory research applications.",
      "Each lot is synthesized via solid-phase peptide synthesis and independently verified for identity and purity using high-performance liquid chromatography and mass spectrometry.",
      "Not for human or veterinary use. Not a drug, food, or cosmetic. For research use only.",
    ],
  },
  {
    slug: "tb-500",
    name: "TB-500",
    category: "Lyophilized Peptides",
    casNumber: "885340-08-3",
    molecularFormula: "C212H350N56O78S",
    molecularWeight: "4963.5 g/mol",
    purityPercent: 98.7,
    sequenceOrForm: "Synthetic fragment of Thymosin Beta-4",
    storage: "Lyophilized powder. Store at -20°C, protect from light and moisture.",
    sizes: [
      { label: "2 mg", priceUsd: 54 },
      { label: "5 mg", priceUsd: 89 },
    ],
    batchNumbers: ["VC-TB5-2409", "VC-TB5-2503"],
    summary: "Synthetic Thymosin Beta-4 fragment, third-party identity and purity confirmed.",
    description: [
      "TB-500 is a synthetic peptide fragment derived from the sequence of Thymosin Beta-4, produced for controlled laboratory research.",
      "Identity is confirmed by mass spectrometry; purity is quantified by reverse-phase HPLC against a certified reference standard.",
      "Not for human or veterinary use. For research use only.",
    ],
  },
  {
    slug: "semaglutide",
    name: "Semaglutide",
    category: "Lyophilized Peptides",
    casNumber: "910463-68-2",
    molecularFormula: "C187H291N45O59",
    molecularWeight: "4113.58 g/mol",
    purityPercent: 99.4,
    sequenceOrForm: "GLP-1 receptor agonist analog, 31 residues",
    storage: "Lyophilized powder. Store at -20°C, protect from light and moisture.",
    sizes: [
      { label: "5 mg", priceUsd: 89 },
      { label: "10 mg", priceUsd: 149 },
    ],
    batchNumbers: ["VC-SEM-2410", "VC-SEM-2501"],
    summary: "31-residue peptide analog, lyophilized, batch-tested via HPLC-MS.",
    description: [
      "Semaglutide is a synthetic 31-amino-acid peptide analog manufactured under controlled conditions for laboratory and analytical research.",
      "Every production lot is assayed for peptide content, purity, and identity prior to release.",
      "Not for human or veterinary use. Not evaluated for any use outside of research. For research use only.",
    ],
  },
  {
    slug: "tirzepatide",
    name: "Tirzepatide",
    category: "Lyophilized Peptides",
    casNumber: "2023788-19-2",
    molecularFormula: "C225H348N48O68",
    molecularWeight: "4813.5 g/mol",
    purityPercent: 99.1,
    sequenceOrForm: "GIP/GLP-1 dual receptor agonist analog, 39 residues",
    storage: "Lyophilized powder. Store at -20°C, protect from light and moisture.",
    sizes: [
      { label: "10 mg", priceUsd: 129 },
      { label: "20 mg", priceUsd: 219 },
    ],
    batchNumbers: ["VC-TIR-2408", "VC-TIR-2502"],
    summary: "39-residue dual-agonist peptide analog, independently verified purity.",
    description: [
      "Tirzepatide is a synthetic 39-amino-acid peptide analog supplied exclusively for in-vitro research and analytical method development.",
      "Identity and purity are confirmed by HPLC-MS against a reference standard for every batch.",
      "Not for human or veterinary use. For research use only.",
    ],
  },
  {
    slug: "epithalon",
    name: "Epithalon",
    category: "Lyophilized Peptides",
    casNumber: "307297-39-8",
    molecularFormula: "C14H22N4O9",
    molecularWeight: "390.35 g/mol",
    purityPercent: 99.6,
    sequenceOrForm: "Ala-Glu-Asp-Gly (tetrapeptide)",
    storage: "Lyophilized powder. Store at -20°C, protect from light and moisture.",
    sizes: [
      { label: "10 mg", priceUsd: 36 },
      { label: "50 mg", priceUsd: 129 },
    ],
    batchNumbers: ["VC-EPI-2407", "VC-EPI-2504"],
    summary: "Synthetic tetrapeptide, high-purity lyophilized powder.",
    description: [
      "Epithalon is a synthetic four-residue peptide chain produced for controlled laboratory research use.",
      "Each batch undergoes identity confirmation and purity assay by HPLC prior to release with a certificate of analysis.",
      "Not for human or veterinary use. For research use only.",
    ],
  },
  {
    slug: "selank",
    name: "Selank",
    category: "Lyophilized Peptides",
    casNumber: "129954-34-3",
    molecularFormula: "C33H57N11O9",
    molecularWeight: "751.87 g/mol",
    purityPercent: 98.9,
    sequenceOrForm: "Thr-Lys-Pro-Arg-Pro-Gly-Pro (heptapeptide analog)",
    storage: "Lyophilized powder. Store at -20°C, protect from light and moisture.",
    sizes: [
      { label: "5 mg", priceUsd: 44 },
      { label: "10 mg", priceUsd: 74 },
    ],
    batchNumbers: ["VC-SEL-2405", "VC-SEL-2501"],
    summary: "Synthetic heptapeptide analog, HPLC-confirmed purity.",
    description: [
      "Selank is a synthetic peptide analog of the endogenous tuftsin sequence, manufactured for laboratory research applications only.",
      "Purity and identity are independently verified by an accredited third-party analytical laboratory for each lot.",
      "Not for human or veterinary use. For research use only.",
    ],
  },
  {
    slug: "nad-plus",
    name: "NAD+",
    category: "Small Molecules",
    casNumber: "53-84-9",
    molecularFormula: "C21H27N7O14P2",
    molecularWeight: "663.43 g/mol",
    purityPercent: 99.0,
    sequenceOrForm: "Nicotinamide adenine dinucleotide (oxidized form)",
    storage: "Lyophilized powder. Store at -20°C, protect from light and moisture.",
    sizes: [
      { label: "100 mg", priceUsd: 39 },
      { label: "500 mg", priceUsd: 149 },
    ],
    batchNumbers: ["VC-NAD-2406", "VC-NAD-2503"],
    summary: "Coenzyme reference compound, lyophilized, purity-verified by HPLC.",
    description: [
      "NAD+ is supplied as a lyophilized powder for use as an analytical reference standard and in laboratory research.",
      "Each lot is quantified for purity by HPLC and confirmed against a certified reference material.",
      "Not for human or veterinary use. For research use only.",
    ],
  },
  {
    slug: "ghk-cu",
    name: "GHK-Cu",
    category: "Small Molecules",
    casNumber: "49557-75-7",
    molecularFormula: "C14H24CuN6O4",
    molecularWeight: "403.94 g/mol",
    purityPercent: 98.5,
    sequenceOrForm: "Gly-His-Lys copper complex",
    storage: "Lyophilized powder. Store at -20°C, protect from light and moisture.",
    sizes: [
      { label: "50 mg", priceUsd: 34 },
      { label: "100 mg", priceUsd: 58 },
    ],
    batchNumbers: ["VC-GHK-2404", "VC-GHK-2502"],
    summary: "Copper-tripeptide complex, lyophilized, identity and purity verified.",
    description: [
      "GHK-Cu is a synthetic copper-binding tripeptide complex intended solely for laboratory and analytical research.",
      "Identity is confirmed by mass spectrometry and purity is assayed by HPLC for every production batch.",
      "Not for human or veterinary use. For research use only.",
    ],
  },
  {
    slug: "aod-9604",
    name: "AOD-9604",
    category: "Peptide Blends",
    casNumber: "221231-10-3",
    molecularFormula: "C78H123N23O23S2",
    molecularWeight: "1815.05 g/mol",
    purityPercent: 98.3,
    sequenceOrForm: "Modified fragment of human growth hormone (176-191)",
    storage: "Lyophilized powder. Store at -20°C, protect from light and moisture.",
    sizes: [
      { label: "2 mg", priceUsd: 46 },
      { label: "5 mg", priceUsd: 79 },
    ],
    batchNumbers: ["VC-AOD-2403", "VC-AOD-2501"],
    summary: "Modified hGH-fragment peptide, batch-certified purity and identity.",
    description: [
      "AOD-9604 is a synthetic modified fragment peptide produced under controlled conditions for in-vitro research use only.",
      "Every batch is analyzed by HPLC-MS to confirm peptide identity and quantify purity prior to release.",
      "Not for human or veterinary use. For research use only.",
    ],
  },
  {
    slug: "ipamorelin-cjc-1295-blend",
    name: "Ipamorelin / CJC-1295 Blend",
    category: "Peptide Blends",
    casNumber: "170851-70-4 / 863288-34-0",
    molecularFormula: "C63H86N16O13 · C152H252N44O42",
    molecularWeight: "1247.4 g/mol · 3367.9 g/mol",
    purityPercent: 98.8,
    sequenceOrForm: "Combined lyophilized pentapeptide and modified GRF(1-29) analog",
    storage: "Lyophilized powder. Store at -20°C, protect from light and moisture.",
    sizes: [
      { label: "5 mg blend", priceUsd: 64 },
      { label: "10 mg blend", priceUsd: 109 },
    ],
    batchNumbers: ["VC-ICB-2402", "VC-ICB-2504"],
    summary: "Two-component lyophilized peptide blend, independently tested by mass ratio.",
    description: [
      "This blend combines two synthetic peptides in a fixed lyophilized ratio, intended solely for laboratory research applications.",
      "Each component is independently verified for identity and purity prior to blending, and the finished lot is re-assayed for combined content.",
      "Not for human or veterinary use. For research use only.",
    ],
  },
];

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getAllBatchNumbers() {
  return products.flatMap((p) => p.batchNumbers.map((b) => ({ batch: b, product: p })));
}
